name: web tunel
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install soft
        run: |
          (echo 'deb http://pkg.cloudflare.com/ focal main' | sudo tee /etc/apt/sources.list.d/cloudflare-main.list )
          (curl -C - https://pkg.cloudflare.com/pubkey.gpg | sudo apt-key add -)
          sudo apt-get update
          sudo apt-get install -y cloudflared
      - name: sonar docker web
        run: |
         docker pull yhlben/notepad
         docker container run -d -p 8080:8083 docker.io/yhlben/notepad
      - name: run cloudflared tunel
        run: cloudflared tunnel
